# Generated by Django 4.0.6 on 2022-08-09 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=2048, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.author')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.country')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this book seria', to='reference_books.genre')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.language')),
                ('publishing_house', models.ManyToManyField(help_text='Select a Publishing House for this book', to='reference_books.publishinghouse')),
            ],
            options={
                'verbose_name_plural': 'Book Series',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('release_number', models.CharField(blank=True, choices=[('1', '1st in series'), ('2', '2st in series'), ('3', '3st in series'), ('4', '4st in series'), ('5', '5st in series'), ('6', '6st in series'), ('7', '7st in series'), ('8', '8st in series'), ('9', '9st in series')], default='1', help_text='Book number in the book series', max_length=1)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('page', models.IntegerField()),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=16, verbose_name='ISBN')),
                ('price', models.FloatField(max_length=8)),
                ('summary', models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=2048, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference_books.author')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference_books.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference_books.currency')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this book', to='reference_books.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference_books.language')),
                ('publishing_house', models.ManyToManyField(help_text='Select a Publishing House for this book', to='reference_books.publishinghouse')),
                ('seria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.bookseria')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
