# Generated by Django 4.0.6 on 2022-07-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_book_publishing_house_book_publishing_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_number',
            field=models.CharField(blank=True, choices=[('1', '1st in series'), ('2', '2st in series'), ('3', '3st in series'), ('4', '4st in series'), ('5', '5st in series'), ('6', '6st in series'), ('7', '7st in series'), ('8', '8st in series'), ('9', '9st in series')], default='1', help_text='Book number in the book series', max_length=1),
        ),
    ]
