# Generated by Django 4.0.6 on 2022-08-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_image_alter_bookseria_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='bookseria',
            old_name='image',
            new_name='pic',
        ),
    ]
