# Generated by Django 4.0.6 on 2022-07-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(db_index=True, max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('symbol', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('founding_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=256, null=True)),
                ('web_site', models.URLField(blank=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookSeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.author')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.country')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.genre')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.language')),
                ('publishing_house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.publishinghouse')),
            ],
            options={
                'verbose_name_plural': 'Book Series',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('release_number', models.CharField(max_length=16)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('page', models.IntegerField()),
                ('isbn', models.CharField(max_length=16, verbose_name='ISBN')),
                ('price', models.FloatField(max_length=8)),
                ('summary', models.TextField(blank=True, max_length=2048, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference_books.author')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference_books.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference_books.currency')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference_books.genre')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference_books.language')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference_books.publishinghouse')),
                ('seria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference_books.bookseria')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='author',
            name='country_of_birth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.country'),
        ),
    ]
