# Generated by Django 4.0.6 on 2022-08-09 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the currency like this: Euro, United States dollar, Japanese yen etc.', max_length=32)),
                ('code', models.CharField(db_index=True, help_text="Enter a graphic symbol used as a shorthand for a currency's name", max_length=16)),
                ('symbol', models.CharField(help_text='Enter ISO 4217 according to this list <a href="https://www.iso.org/iso-4217-currency-codes.html"></a>', max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=32)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)", max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32)),
                ('founding_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, help_text='Enter full address including courty, state etc.', max_length=256, null=True)),
                ('web_site', models.URLField(blank=True, help_text='Enter web-site like this: https://antipetrun86.pythonanywhere.com', null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(db_index=True, max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, max_length=2048, null=True)),
                ('country_of_birth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.country')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
