# Generated by Django 4.0.6 on 2022-07-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=32, verbose_name='Last Name')),
                ('short_name', models.CharField(max_length=32, verbose_name='Short Name')),
                ('country_birth', models.CharField(max_length=32, verbose_name='Country of Birth')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('biography', models.TextField(max_length=256, verbose_name='Biography')),
            ],
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('original_name', models.CharField(max_length=32, verbose_name='Original Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('author', models.CharField(max_length=32, verbose_name='Author')),
                ('genre', models.CharField(max_length=32, verbose_name='Genre')),
                ('country', models.CharField(max_length=32, verbose_name='Country')),
                ('language', models.CharField(max_length=32, verbose_name='Language')),
                ('publish_house', models.CharField(max_length=32, verbose_name='Publishing House')),
                ('publish_date', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Publication Date')),
                ('rus_publish_date', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Publication Date on Russian')),
            ],
        ),
        migrations.CreateModel(
            name='LiteraryGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('description', models.TextField(max_length=256, verbose_name='Biography')),
            ],
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('country', models.CharField(max_length=32, verbose_name='Country')),
                ('founding_date', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Founding Date')),
                ('address', models.TextField(max_length=256, verbose_name='Address')),
                ('web_site', models.URLField(blank=True, null=True, verbose_name='Web Site')),
            ],
        ),
    ]
