# Generated by Django 4.0.6 on 2022-07-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0002_remove_bookseries_publish_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='bookseries',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='<django.db.models.fields.CharField> <django.db.models.fields.CharField>', max_length=32, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='author',
            name='country_birth',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Country of Birth'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='country',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='language',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='publish_house',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Publishing House'),
        ),
        migrations.AlterField(
            model_name='literarygenre',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='address',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='country',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Country'),
        ),
    ]
