# Generated by Django 4.0.6 on 2022-07-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0003_remove_author_short_name_remove_bookseries_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=32, verbose_name='Full Name'),
        ),
    ]
