# Generated by Django 4.0.6 on 2022-07-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0003_alter_book_isbn_alter_book_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookseria',
            name='description',
        ),
        migrations.AddField(
            model_name='bookseria',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(db_index=True, help_text="Enter a graphic symbol used as a shorthand for a currency's name", max_length=16),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(help_text='Enter the currency like this: Euro, United States dollar, Japanese yen etc.', max_length=32),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(help_text='Enter ISO 4217 according to this list <a href="https://www.iso.org/iso-4217-currency-codes.html"></a>', max_length=16),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='address',
            field=models.TextField(blank=True, help_text='Enter full address including courty, state etc.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='web_site',
            field=models.URLField(blank=True, help_text='Enter web-site like this: https://antipetrun86.pythonanywhere.com', null=True),
        ),
    ]
