# Generated by Django 4.0.6 on 2022-07-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0004_remove_bookseria_description_bookseria_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookseria',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookseria',
            name='country',
        ),
        migrations.RemoveField(
            model_name='bookseria',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookseria',
            name='language',
        ),
        migrations.RemoveField(
            model_name='bookseria',
            name='publishing_house',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookSeria',
        ),
    ]
