# Generated by Django 4.0.6 on 2022-07-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0005_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Language')),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
    ]
