# Generated by Django 4.0.6 on 2022-07-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0006_language_alter_country_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='bookseries',
            options={'ordering': ['name'], 'verbose_name': 'Book Series', 'verbose_name_plural': 'Book Series'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='literarygenre',
            options={'ordering': ['name'], 'verbose_name': 'Literary Genre', 'verbose_name_plural': 'Literary Genres'},
        ),
        migrations.AlterModelOptions(
            name='publishinghouse',
            options={'ordering': ['name'], 'verbose_name': 'Publishing House', 'verbose_name_plural': 'Publishing Houses'},
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='literarygenre',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='Name'),
        ),
    ]
