# Generated by Django 4.0.6 on 2022-07-17 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0008_bookseries_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookseries',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.literarygenre', verbose_name='Genre'),
        ),
    ]
