# Generated by Django 4.0.6 on 2022-07-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0010_remove_bookseries_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookseries',
            name='genres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.literarygenre', verbose_name='Genre'),
        ),
    ]
