# Generated by Django 4.0.6 on 2022-07-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0011_bookseries_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookseries',
            old_name='genres',
            new_name='genre',
        ),
    ]
