# Generated by Django 4.0.6 on 2022-07-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0012_rename_genres_bookseries_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookseries',
            name='country',
        ),
        migrations.RemoveField(
            model_name='bookseries',
            name='language',
        ),
    ]
