# Generated by Django 4.0.6 on 2022-07-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0013_remove_bookseries_country_remove_bookseries_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookseries',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.language', verbose_name='Language'),
        ),
    ]
