# Generated by Django 4.0.6 on 2022-07-17 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0015_remove_bookseries_publish_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookseries',
            name='publishing_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_books.publishinghouse', verbose_name='Publishing House'),
        ),
    ]
