# Generated by Django 4.0.6 on 2022-07-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0016_bookseries_publishing_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='country_birth',
        ),
        migrations.RemoveField(
            model_name='publishinghouse',
            name='country',
        ),
    ]
