# Generated by Django 4.0.6 on 2022-07-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0018_author_country_birth_publishinghouse_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='literarygenre',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Biography'),
        ),
    ]
