# Generated by Django 4.0.6 on 2022-07-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0019_alter_author_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literarygenre',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description'),
        ),
    ]
