# Generated by Django 4.0.6 on 2022-07-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0021_currency_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(verbose_name='ISBN'),
        ),
    ]
