# Generated by Django 4.0.6 on 2022-07-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0022_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='bookseries',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Description'),
        ),
    ]
