# Generated by Django 4.0.6 on 2022-07-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0023_book_description_bookseries_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name'], 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
