# Generated by Django 4.0.6 on 2022-07-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0024_alter_currency_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(db_index=True, max_length=16, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(db_index=True, max_length=16, verbose_name='Symbol'),
        ),
    ]
