# Generated by Django 4.0.6 on 2022-07-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0025_alter_currency_code_alter_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=16, verbose_name='Pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page',
            field=models.IntegerField(verbose_name='Pages'),
        ),
    ]
