# Generated by Django 4.0.6 on 2022-07-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0026_alter_book_isbn_alter_book_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code'], 'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=16, verbose_name='ISBN'),
        ),
    ]
