# Generated by Django 4.0.6 on 2022-07-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0027_alter_currency_options_alter_book_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rus_release_date',
        ),
        migrations.RemoveField(
            model_name='bookseries',
            name='rus_release_date',
        ),
    ]
