# Generated by Django 4.0.6 on 2022-07-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0028_remove_book_rus_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_name',
            field=models.CharField(max_length=64, verbose_name='Original Name'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='original_name',
            field=models.CharField(max_length=64, verbose_name='Original Name'),
        ),
    ]
