# Generated by Django 4.0.6 on 2022-08-22 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='buyer',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular order', primary_key=True, serialize=False),
        ),
    ]
