# Generated by Django 4.0.6 on 2022-08-22 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_comment_order_delivery_address_order_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
    ]
