# Generated by Django 4.0.6 on 2022-08-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in work', 'in work'), ('canceled', 'canceled'), ('delivered', 'delivered')], default='in work', help_text='Status of the Order', max_length=9),
        ),
    ]
